---
platform: linux
image_resource:
  type: docker-image
  source: {repository: "allomov/ruby", tag: "manifest-generator"}
inputs:
  - name: merrill-manifest-generator-dev
run:
  path: ci/scripts/run-tests
  dir: merrill-manifest-generator-dev/manifest-generator
